name: Feature request
description: Suggest an idea for a feature that improves Borderless gaming
title: A concise title that best describes the feature
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have you got a suggestion for borderless gaming?
  - type: checkboxes
    attributes:
      label: Requirements
      description: Before you create a suggestion, please consider the following
      options:
        - label: Did you check if this issue already exists?
          required: true
        - label: Is this only a single feature request? Please file multiple issues if you have multiple suggestions.
          required: true
  - type: textarea
    id: problem
    attributes:
      label: Is this proposal related to a problem?
      description: |
        Provide a description of what the problem is.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like.
      description: |
        Provide a concise description of what solution you're proposing.
        Have you thought of alternative solutions?
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: |
        Is there anything else worth mentioning, that is related to this issue?
        Maybe there are related issues that can be mistaken for duplicates, describe why they aren't